### ISSUE TITLE
[Bug]uncaught ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

### ISSUE THREAD

**Issue by Othman2001** [salgum1114/react-design-editor#232]
**Describe the bug**
1. i extracted the code of ImageMapEditor & canvas , handlers , all of the project code except the code of other editors.
2. and added this to my existing  create-react-app 
3. i had some issues but i solved it except this bug 
when i call the ImageMapEditor in the App it fires this error in the console

**Comment by Othman2001** [comment]
this is the error 
```
GuidelineHandler.ts:378 Uncaught ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (GuidelineHandler.ts:378:1)
    at Module.Handler (ZoomHandler.ts:152:1)
    at registerExportsForReactRefresh (RefreshUtils.js:147:1)
    at Object.executeRuntime (RefreshUtils.js:182:1)
    at $ReactRefreshModuleRuntime$ (index.ts:43:1)
    at Module../src/modules/editor/components/canvas/handlers/index.ts (index.ts:43:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module../src/modules/editor/components/canvas/handlers/Handler.ts (GuidelineHandler.ts:378:1)
```

**Comment by AndreasBurbach** [comment]
You still get this error after your pull request?

**Comment by Othman2001** [comment]
i have fixed this error by pull request at this repo : 
https://github.com/AndreasBurbach/react-image-design-editor
i will try to fix it here for both imageMap Editor and workflow editor and make pull request
